### ISSUE TITLE
[Question] How to record audio from input and stream to output?

### ISSUE THREAD

**Issue by DuckerMan** [RustAudio/cpal#421]
I've tried an example, but it hasn't compiled

**Comment by mitchmindtree** [comment]
@DuckerMan the `examples/feedback.rs` example is aimed at demonstrating how to achieve this. Ideally we'll eventually support duplex streams #349 but until then this approach should work for a lot of cases.

If you have tried running the example and it is has failed to compile or produced some kind of error, could you provide the error output and some details about which platform you're testing on etc so that we may try and recreate the issue?

**Comment by DuckerMan** [comment]
Hi! It seems that examples doesnt work on crates.io version, but do work with github version; Thanks :)
