### ISSUE TITLE
Is there any reason for not using dasp-sample ?

### ISSUE THREAD

**Issue by dheijl** [RustAudio/cpal#488]
cpal provides its own sample conversions, with limitations like no I24 support.
dasp-sample does all this and more, so why duplicate something that already exists?

**Comment by mitchmindtree** [comment]
I kicked off `dasp` (originally `sample`) quite a while after the `cpal` project began and before the `cpal` crate was moved under the `RustAudio` umbrella.

`dasp` used to be a single crate, with quite a few modules unrelated to `cpal`'s needs, however since `dasp` was recently split into sub-crates (e.g. `dasp-sample`, `dasp-slice`, etc) I think it makes more sense to consider `dasp-sample` for the `Sample` trait abstraction.

**Comment by dheijl** [comment]
OK Thanks for the explanation! I was thinking of I24 sample format support.

**Comment by Be-ing** [comment]
It would be great to refactor cpal to use dasp wherever possible. I think using dasp traits in this foundational library could go a long way into unifying the ecosystem around dasp so libraries are easily interoperable.

**Comment by Be-ing** [comment]
@dheijl could you reopen this? Your question was answered, but the refactoring has not been done yet.
