### ISSUE TITLE
losing audio input stream data, where portaudio does not

### ISSUE THREAD

**Issue by debamitro** [RustAudio/cpal#619]
I am learning Rust and audio signal processing. I wrote a very small program for collecting audio data from my microphone, and although I set the sampling rate at 44100 Hz I was getting a few hundred samples only. After making the callback function more lightweight, and using a release build I could get around 43000 samples per second. For a comparison I took a recorder example from the portaudio codebase and ran it - I got 44100 samples every time.

What could be going wrong? I am getting a feeling that CoreAudio might be dropping the samples, and portaudio did some additional work to catch them. Please suggest any ideas for investigating further.

**Comment by PieterPenninckx** [comment]
It's hard to tell without the actual source code. Maybe you're doing something that blocks the callback function like writing data to disk or any input-output really See [this blog post](http://www.rossbencina.com/code/real-time-audio-programming-101-time-waits-for-nothing) for why this is a bad idea. If this is the problem, you can use the [rtrb](https://crates.io/crates/rtrb) crate for sending the data to another thread (or maybe [creek](https://crates.io/crates/creek) for the purpose of streaming to disk).

What do you mean by "getting a few hundred samples only"? What happens after that? Does it crash, is the callback function no longer called, ...?

**Comment by debamitro** [comment]
Thanks for the reply. I have kept my callback function really light-weight: I only update the number of samples received, using an atomic operation. [Here](https://gist.github.com/debamitro/36edbe3344049b401754f757eedd9044) is a gist showing my code. I just ran this with a release build and got 1717248 samples over 20 seconds. Given that the data is 2-channel, the number of samples per second is 1717248 / 2 / 20, which comes to 42931.

**Comment by PieterPenninckx** [comment]
Aww, you dragged me into the domain of multi-threaded programming here ;-)

Thank you for the code sample. I have three suspects:
* Idea: "`stream.play()` actually takes some time to get started". This could explain it, but it looks like `stream.play()` under the hood [actually](https://docs.rs/cpal/0.13.4/src/cpal/host/alsa/mod.rs.html#958) [calls](https://docs.rs/alsa/latest/src/alsa/pcm.rs.html#136) the C function [`snd_pcm_pause`](https://www.alsa-project.org/alsa-doc/alsa-lib/group___p_c_m.html#gad711b582c7066bd4fffa1d08a04316b5) and not much more, so `stream.play()` may actually not be causing the delay. I don't know.
* ~You're using an `Arc`. If I'm correct, an `Arc` uses a synchronisation mechanism that may block the audio thread for a while, hence it's not advised to use `Arc` in a real-time context. I don't think this is the actual cause since an `Arc` will be fast enough _most of the time_, which is probably ok for tests like this, but not when you're using it in a plugin in a live concert.~ I was probably wrong here: the `Arc` is not cloned or deleted in the real-time context, so this shouldn't be a problem.
* You're using `Relaxed` ordering. This looks suspicious to me. According to [the documentation from the Nomicon](https://doc.rust-lang.org/nomicon/atomics.html), this should be fine "if you're not using the counter to synchronize any other accesses". I honestly don't fully understand what they mean by that; maybe it's not fine and increasing the counter gets delayed until after the counter is printed?

Ideas:
* Can you try running the test with `SeqCst` ordering and see if that helps?
* What is the example from the PortAudio codebase? Does it also use `snd_pcm_pause` under the hood, or does it something else?

**Comment by debamitro** [comment]
I don't think the 'snd_pcm_pause' flow is for MacOS. My guess is that [this](https://github.com/RustAudio/cpal/blob/b9511a21a526c3df0d61f8ca37001a873e792982/src/host/coreaudio/macos/mod.rs#L803) is the code executing on MacOS, which in turn calls the [AudioOutputUnitStart](https://github.com/RustAudio/coreaudio-rs/blob/b3e605f2001db0a87c17c14eefbcba37e98f0498/src/audio_unit/mod.rs#L245) API. I have been trying to compile cpal from source in order to investigate further. I ran into a build issue in coreaudio-sys the other day, I'll try again.

I am still clueless and I will try changing the memory ordering to see if that helps. 

Meanwhile, I started doing some more stuff in my callback and the number of samples came down even more, to ~39000. It is possible that the usage of reference-counted pointers to atomic variables is not lightweight enough for the callback. If that's what this boils down to, then I need to scratch my head about alternative approaches.

**Comment by debamitro** [comment]
I found out that this is really not a bug, but rather a slight difference in how cpal and portaudio process the user's callback function. Portaudio lets a callback function specify whether it needs to be called again. Cpal does not seem to do that. So it is up to the user of cpal to ensure that the input stream remains open until all the samples expected have arrived.
