### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by Jasper-Bekkers** [RustAudio/cpal#744]
We're currently on a git dependency because we need the updated oboe dependency for android support (it updates the ndk dependency to be inline with winit and others). Would you be so kind to release an update of cpal? Currently android support is broken because of this when used in conjunction with winit.

For an explainer, please see https://github.com/katyo/oboe-rs/issues/46

**Comment by est31** [comment]
Due to 85d773d59f1725b25002c6f04aa2eb9b43a75b76 and 29999e6857be4bd4cd04a8a80fdc5ab07e1172a9 both of which are API breaking changes, the next release will be 0.15.0. The latter is platform dependent, but the former affects all platforms.

I will first make a PR to update the dependencies, then if CI is fine, I will do another PR to make a release, ideally today.
